# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform FMD Server installation tasks
  when: fmd_server_enabled | bool
  tags:
    - setup-all
    - setup-fmd-server
    - install-all
    - install-fmd-server
  block:
    - name: Validate FMD Server configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install FMD Server
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform FMD Server uninstallation tasks
  when: not fmd_server_enabled | bool
  tags:
    - setup-all
    - setup-fmd-server
  block:
    - name: Uninstall FMD Server
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
