# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform FMD Server installation tasks
  block:
    - name: Validate FMD Server configuration
      when: fmd_server_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install FMD Server
      when: fmd_server_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-fmd-server
    - install-all
    - install-fmd-server

- name: Perform FMD Server uninstallation tasks
  block:
    - name: Uninstall FMD Server
      when: not fmd_server_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-fmd-server
