# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of FMD Server systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ fmd_server_identifier }}.service"
  register: fmd_server_service_stat

- when: fmd_server_service_stat.stat.exists | bool
  block:
    - name: Ensure FMD Server systemd service is stopped
      ansible.builtin.service:
        name: "{{ fmd_server_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure FMD Server systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ fmd_server_identifier }}.service"
        state: absent

    - name: Ensure FMD Server path does not exist
      ansible.builtin.file:
        path: "{{ fmd_server_base_path }}"
        state: absent
