# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of FMD Server systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ findmydeviceserver_identifier }}.service"
  register: findmydeviceserver_service_stat

- when: findmydeviceserver_service_stat.stat.exists | bool
  block:
    - name: Ensure FMD Server systemd service is stopped
      ansible.builtin.service:
        name: "{{ findmydeviceserver_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure FMD Server systemd service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ findmydeviceserver_identifier }}.service"
        state: absent

    - name: Ensure FMD Server base directory doesn't exist
      ansible.builtin.file:
        path: "{{ findmydeviceserver_base_path }}"
        state: absent
