# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: (Deprecation) Catch and report old findmydeviceserver variables
  ansible.builtin.fail:
    msg: |-
      The role has been renamed from ansible-role-findmydeviceserver to ansible-role-fmd-server after the upstream project has been rebranded. Following it the variables of the role have also been renamed.

      Please change your configuration file (vars.yml) to rename all `fmd_server_`-prefixed variables (`findmydeviceserver_*` -> `fmd_server_*`).

      The following variables in your configuration need to be renamed: {{ vars | dict2items | selectattr('key', 'match', 'findmydeviceserver_.*') | map (attribute='key') | join(', ') }}
  when: "vars | dict2items | selectattr('key', 'match', 'findmydeviceserver_.*') | list | items2dict"

- name: Fail if required FMD Server settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - findmydeviceserver_uid
    - findmydeviceserver_gid
    - findmydeviceserver_hostname
    - findmydeviceserver_path_prefix
    - findmydeviceserver_container_network
    - findmydeviceserver_database_path

- when: findmydeviceserver_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required FMD Server Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - findmydeviceserver_container_labels_traefik_hostname
        - findmydeviceserver_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `findmydeviceserver_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if findmydeviceserver_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          findmydeviceserver_container_labels_traefik_path_prefix (`{{ findmydeviceserver_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/findmydeviceserver`).
      when: "findmydeviceserver_container_labels_traefik_path_prefix != '/' and findmydeviceserver_container_labels_traefik_path_prefix[-1] == '/'"
